### ISSUE TITLE
#US93: Como miembro del equipo de desarrollo, quiero que ambos proyectos cumplan con las normas básicas de accesibilidad para facilitar el acceso a todo tipo de público en igualdad de oportunidades. 

### ISSUE THREAD

**Issue by GiulianaDeEt** [projects-ISPC/practicaProfesionalizante-ISPC#93]
- [x] #TK01: Incluir texto alternativo en todas las imágenes de la aplicación.
- [x] #TK02: Asegurar que el contenido de la aplicación es comprensible y de fácil acceso a los usuarios.
- [x] #TK03: Agregar funcionamiento del lector de pantalla.

**Comment by Vibianco** [comment]
No se observan fallas de accesibilidad al día de la fecha. Se realizarán nuevamente las pruebas pertinentes al final del sprint.
